plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'
    id 'com.github.spotbugs' version "6.4.2"
}

group = 'com.bugmaker'
version = '0.0.1-SNAPSHOT'
description = '아파트 프로젝트'

checkstyle {
    toolVersion = '10.12.4'
    ignoreFailures = true
}

// 테스트 Java 소스 컴파일 비활성화
tasks.named('compileTestJava') {
	enabled = false
}

// 테스트 리소스 처리 비활성화 (선택 사항이지만 깔끔합니다)
tasks.named('processTestResources') {
	enabled = false
}

// ===== 테스트 비활성화 =====
tasks.named("test") {
	enabled = false
}

tasks.named("check") {
	enabled = false
}

// ===== SpotBugs 비활성화 =====
tasks.named("spotbugsMain") {
	enabled = false
}

tasks.named("spotbugsTest") {
	enabled = false
}

// ===== Checkstyle: test 제외, main만 검사 =====
tasks.named("checkstyleTest") {
	enabled = false
}

tasks.named("checkstyleMain") {
	enabled = false
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    runtimeOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Lombok
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	
	// PostgreSQL
	runtimeOnly 'org.postgresql:postgresql'

	// OAuth2 Client
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	
	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	
	// Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(Checkstyle).configureEach {
    reports {
        xml.required = false
		html.required = true
    }
}

test {
    jvmArgs "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('mockito-core') }}", '-Xshare:off'
}

spotbugs {
    excludeFilter.set(file("${projectDir}/spotbugs-exclude-filter.xml"))
}
