spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
    show-sql: false
