spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.201.77.236:5432/dev_bugmaker
    username: bugmaker
    password: exit_bitmax
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        use_sql_comments: true
    show-sql: false
